### ISSUE TITLE
Getting `undefined is not a function`

### ISSUE THREAD

**Issue by roshanpaiva** [IonicaBizau/node-ipinfo#10]
When i run this code 

``` javascript
var ipInfo;
ipInfo = require("ipinfo");
ipInfo("50.202.37.133", function(err, cLoc) {
  console.log(err || cLoc);
});
```

I get `undefined is not a function`. Traced it down to the fact that jsonRequest is using ul 5.2.4. This causes it to return 

``` javascript
{code: "ECONNREFUSED",
errno: "ECONNREFUSED",
message: "connect ECONNREFUSED",
stack: undefined,
syscall: "connect"}
```

Hope this is helpful.

**Comment by IonicaBizau** [comment]
It happened due to a mistake in the previous version of `ul` (the tests were not covering that use-case also).

Fixed in the latest patch release of [`ul`](https://github.com/IonicaBizau/node-ul). `npm update` should be enough to fix the things. :rocket:
