### ISSUE TITLE
Unit testing with ipInfo

### ISSUE THREAD

**Issue by souly1** [IonicaBizau/node-ipinfo#5]
Hi Ionică Bizău, great module.
I'm having trouble stubbing ipinfo during unit tests using mocha+sinon+proxyquire, I presume it mainly due it not returning  an object during require.
Tried to follow some explanations on proxy quire page for how to test the module, but in vane.
any recommendations?

Thanks

**Comment by IonicaBizau** [comment]
Are you trying to redirect somehow the request to not make the http request to `ipinfo.io` but to `localhost`?

If so, you can override the `IpInfo.HOSTNAME` during the tests.

I'm not sure if this is what you need, tho. :thought_balloon:

**Comment by souly1** [comment]
Hi, thanks for the reply. Basically what I need is when code attempts to run ip info in this manner:
ipinfo(ip, function (err, cLoc) {});
the code in 'node_modules/ipinfo/lib/index' be run but instead mine will be run, basically returning my wanted err or cLoc, and with Sinon's ability, will be able to notify if code indeed reached at all or not using mock.called() which returns true if indeed function called. the later ability, with Sinon, is less important as one can simulate the behaviour with a simple flag in the mock implementation of ipinfo.
Hope this helps.

Thanks

**Comment by IonicaBizau** [comment]
Ah, I see what you mean.

Yes, probably because it's exporting a function, `proxyquire` can't override it. But like I mentioned before, you can override the `HOSTNAME` field to a localhost server where you send the custom response.

I would recommend opening an issue in `proxyquire` to double check if overriding the module behavior is possible. Not quite sure.

**Comment by souly1** [comment]
OK, give an update here if you discover a solution or plan to add support for unit testing.
Thanks

**Comment by IonicaBizau** [comment]
Discussed here: https://github.com/thlorenz/proxyquire/issues/120

Glad to see the issue was fixed.
