### ISSUE TITLE
Support HTTPS and Token

### ISSUE THREAD

**Issue by nokkypx** [IonicaBizau/node-ipinfo#7]
Registered user support (include https)

i have made a change and added the support, did not manage to make a pull request so here are the updated code lines :

```
var IpInfo = module.exports = function (type, token, callback) {

url = null;
    if(token != undefined) { 
        if (typeof type === "function") {
            url = IpInfo.HOSTNAME_SSL  + "/json" + IpInfo.TOKEN_PREFIX + token;
            callback = type;
        } else if (IpInfo.IP_REGEX.test(type)) {
            url = IpInfo.HOSTNAME_SSL  + type + "/json" + IpInfo.TOKEN_PREFIX + token;
        } else {
            url = IpInfo.HOSTNAME_SSL  + type + IpInfo.TOKEN_PREFIX + token;
        }
    } else {
        if (typeof type === "function") {
            url = IpInfo.HOSTNAME + "json";
            callback = type;
        } else if (IpInfo.IP_REGEX.test(type)) {
            url = IpInfo.HOSTNAME + type + "/json";
        } else {
            url = IpInfo.HOSTNAME + type;
        }
    }

    JsonRequest(url, callback);
};

// Constants
IpInfo.HOSTNAME = "http://ipinfo.io/";
IpInfo.HOSTNAME_SSL = "https://ipinfo.io/";
IpInfo.TOKEN_PREFIX = "?token=";
IpInfo.IP_REGEX = /^\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b$/;
```

**Comment by IonicaBizau** [comment]
@nokkypx That's amazing! ✨ Well, just create a pull request with this change. I'll be happy to add this feature.

If I'm not wrong we could always use the `https` protocol.

**Comment by nokkypx** [comment]
Glad you liked it :)
I tried to follow your convention.

The HTTPS is only supported for subscribed(paying) customers.

**Comment by nokkypx** [comment]
any info on when can this be merged into the code ? 
would love to use the module straight from NPM without having to edit it manually.
Cheers 👍

**Comment by IonicaBizau** [comment]
@nokkypx Please create a PR. I'm around for few minutes and happy to merge it. 😁 

I'm currently traveling in England, so I'm potentially unavailable few days.

**Comment by nokkypx** [comment]
ohh it is ok then,
i shall wait for your return, i am not able to create PR at the moment, having computer issues, am replying by mail.

i have noticed a change needed in the JSON_REQUEST module used, it needs to support the HTTPS module as well as the HTTP module, depending on the request.

I have made the change locally, but if you merge the code above you would be required to make that change as well.

Cheers, enjoy england.

**Comment by IonicaBizau** [comment]
No worries, I'm going to take care of it.

**Comment by IonicaBizau** [comment]
🚢 **`1.3.0`** 🎉

**Comment by nokkypx** [comment]
Thank you so much,
it is highly appreciated 💯
